Hometask 3
Mirovitska/AQA_API_TEAMCITY pull request #5
Opened 2024-02-09 21:30 UTC by Mirovitska

2024-02-13 02:36 UTC, AlexPshe requested changes
Привет! 

Большое спасибо за качественное выполнение задания ⚡️

Нужно поправить один коммент и будет зачтено 🔥

2024-02-13 02:36 UTC, AlexPshe commented on src/main/java/com/example/teamcity/ui/pages/AgentPage.java
> +    private final SelenideElement authorizeButton = $x("//div[contains(@class, 'AuthorizeAgent__authorizeAgent--Xr')]//button");
Подскажи, а почему авторизация агента через UI, а не API? 
Обычно у нас очень прагматичный подход "все, что можно вынести на уровень ниже в API, мы выносим в API" из-за стабильности и скорости тестов. Поэтому предлагаю вынести в API.

2024-02-14 16:52 UTC, Mirovitska commented on src/main/java/com/example/teamcity/ui/pages/AgentPage.java
> +    private final SelenideElement authorizeButton = $x("//div[contains(@class, 'AuthorizeAgent__authorizeAgent--Xr')]//button");
Привет, добавила авторизацию агента через АПИ

2024-02-15 12:43 UTC, AlexPshe approved these changes
Отлично, зачтено!

2024-02-15 12:52 UTC, merged